---
AWSTemplateFormatVersion: '2010-09-09'
Description: my template description
Metadata:
  foo: bar
Parameters:
  foo:
    Type: String
  bar:
    Type: String
    Description: This is the bar parameter
    Default: bar
    AllowedValues:
    - foo
    - bar
    ConstraintDescription: only foo bar allowed
  ec2ami:
    Type: String
    Description: ami id for the ec2 image
Resources:
  myInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: ec2ami
      InstanceType: t1.micro
Outputs:
  myoutput:
    Value: my value
    Description: my description
    Export:
      Name: name-of-my-exported-value
